### ISSUE TITLE
2023-12 - December BitDevs!

### ISSUE THREAD

**Issue by humansinstitute** [PerthBitDevs/PerthBitDevs#1]
Please suggest topics to discuss at the inaugural Perth Bit Devs at Phat Brew ⚡️💻

During the session we'll go through each topic and figure out as a group what it is about, the technical underpinnings, and implications and any Q&A people have. The plan is to grow and get understand bitcoin better!

Share any recent topics on this GitHub issue: Bitcoin, news, free software, tech, privacy, or related!

**Comment by chef4brains** [comment]
See you there!

**Comment by NoSandMan** [comment]
Best ROI when investing effort to increase adoption. Should we be focusing on family, circular economy, niche vendors etc.

**Comment by humansinstitute** [comment]
Pools per bitcoin 

https://x.com/DSBatten/status/1729967479148237100?s=20

**Comment by humansinstitute** [comment]
The 84 BTC Fee

https://x.com/mononautical/status/1727627818929094973?s=20

**Comment by humansinstitute** [comment]
Lightning Stable Channels 

https://x.com/tonklaus/status/1729567459579945017?s=20

**Comment by humansinstitute** [comment]
Few other stable options:

- 10101 - https://10101.finance/
- Fedimint Stabilty Pools https://github.com/nope78787/stabilitypool

**Comment by humansinstitute** [comment]
"OP threw a 5"

https://www.reddit.com/r/coldcard/comments/17epqk8/040_bitcoin_taken_instantly_from_my_coldcard/

**Comment by humansinstitute** [comment]
OCEAN - non-custodial mining pool (? sort of... ?) 

https://ocean.xyz/

**Comment by humansinstitute** [comment]
Mutiny blocks Zeus Pay lightning addresses

https://primal.net/e/note1h0lqfkm0neywkmsvuyv69gfgfa6pwmj6aay9vau804hrpgvlfkhqszvfj9
