### ISSUE TITLE
2024-07 July BitDevs

### ISSUE THREAD

**Issue by NoSandMan** [PerthBitDevs/PerthBitDevs#10]
Perth BitDevs - Bitcoin Socratic Seminar -  4th of July 2024!

Thu, 4th of July · 6:00 PM AWST at Phat Brew Brewery in City West.

Please leave discussion topics below.

**Comment by NoSandMan** [comment]
![GQWx6XCXUAAOj77.png](https://github.com/humansinstitute/PerthBitDevs/assets/104331906/2c6bf029-0864-45f1-aa3d-e89d9dae6d6f)

**Comment by NoSandMan** [comment]
Hunter beast proposed BIP to introduce quantum resistance to bitcoin.  

https://x.com/bitcoinoptech/status/1801540608781107393

**Comment by NoSandMan** [comment]
Trezor releases new mnemonic back up standard SLIP-0039 to improve BIP-0039

https://trezor.io/learn/a/multi-share-backup-on-trezor

**Comment by NoSandMan** [comment]
On governments selling bitcoin:

https://x.com/ArkhamIntel/status/1803808325391335619

**Comment by NoSandMan** [comment]
EU e2e find signal article

**Comment by NoSandMan** [comment]
Burak does it again!

Introducing Brollups: a Bitcoin-native rollup design that works with a native Bitcoin peg and requires no changes to the Bitcoin protocol.

https://x.com/brqgoo/status/1803973553458425997

**Comment by btc-alchemist** [comment]
Busso Bash Chat

**Comment by btc-alchemist** [comment]
Seedsigner multisig demo & general rundown

**Comment by NoSandMan** [comment]
Cusf

**Comment by chef4brains** [comment]
https://x.com/nneuman/status/1816862638900658562?s=46
