### ISSUE TITLE
2024-09 September BitDevs - The WA BUSH BitDevs !!

### ISSUE THREAD

**Issue by humansinstitute** [PerthBitDevs/PerthBitDevs#12]
Perth BitDevs - Bitcoin Socratic Seminar - 6th September 2024!

Sunday Sept 8th  · 11:00 AM AWST at Shelter Brewing, Busselton.

Please leave discussion topics below.

This will be a special edition Bush Bitdevs at the WA Bitcoin Bush Bash!

https://x.com/WABBB_21/status/1805506087690416230

**Comment by humansinstitute** [comment]
![Bitcoin-Bush-Bash-Poster](https://github.com/user-attachments/assets/a80df0d4-d975-461e-8f2a-7bb9b859c029)

**Comment by humansinstitute** [comment]
BitVM2 Bridges

Tweet
https://x.com/robin_linus/status/1824004440099053949?s=46

Whitepaper 
https://bitvm.org/bitvm_bridge.pdf

**Comment by tahitilooksnice** [comment]
How to recover a wallet from an Xpub wallet config

**Comment by humansinstitute** [comment]
Tidying up this in private right now but will release before hand to talk about a new side project :) 

Avalon a low barrier entry point to free information, money and social. 

https://github.com/humansinstitute/avalon

**Comment by btc-alchemist** [comment]
Some main topics to possibly discuss after:

Mining - Bitaxe Home Mining. Centralisation of mining pools. Who is manufacturing chips? Where will Bitcoins thirst for energy lead humanity?
Nostr - Online privacy, and recent developments with Telegram. Can we win when they have Pegasus?
Seedhammer - Multisig setup using a seedsigner. You don't even need to use one to sign transactions... (Dark Skippy and verifying software)
SeedXOR - Split your seed. How does it work, and why would you want to use it?
Meshtastic - How can we broadcast transactions with a hand radio?

**Comment by murray-mc** [comment]
Possible Topic:

NOSTR and e-cash
https://youtu.be/OHqxp-Hrx9k?si=HRms719K6d18vGLa

**Comment by humansinstitute** [comment]
Brazil and VPNs

Trust models and Obscura

https://x.com/obscuravpn/status/1825972983178944543?s=46

**Comment by humansinstitute** [comment]
Bolt 12 live on LND-K by Strike

https://x.com/moneyball/status/1831122061437100347?s=46

**Comment by humansinstitute** [comment]
Nocholas Dorier on eCash as an antidote to tokens and private monies. 

https://blog.nicolas-dorier.com/posts/cashu/

**Comment by humansinstitute** [comment]
Bitcoin mining developer list

https://groups.google.com/g/bitcoinminingdev/c/97fkfVmHWYU?pli=1

**Comment by humansinstitute** [comment]
Covenant and Layer 2 Analysis by Peter Todd

https://petertodd.org/2024/covenant-dependent-layer-2-review

**Comment by humansinstitute** [comment]
Frost based lightning!!! 👀👀

**Comment by chef4brains** [comment]
https://albyhub.com/

**Comment by NoSandMan** [comment]
https://conduition.io/mercury-disclosure-f893472ec3128de1.html

**Comment by btc-alchemist** [comment]
Orangels
