### ISSUE TITLE
2024-03 - March Bitdevs!

### ISSUE THREAD

**Issue by humansinstitute** [PerthBitDevs/PerthBitDevs#5]
Please leave ideas below - details to follow.

**Comment by humansinstitute** [comment]
Bitstake

Proof of stake side chain bridge using proof of stake mechanics based on bitVM. 

https://x.com/lightcoin/status/1757502107811275143?s=46

**Comment by humansinstitute** [comment]
Quick explanation of UTXO consolidation / management when to withdraw from exchange's

**Comment by chef4brains** [comment]
https://x.com/marathondh/status/1760760058281910309?s=46

**Comment by chef4brains** [comment]
Braiins are the first pool to implement lighting payouts.

https://x.com/braiinsmining/status/1760319741560856983?s=46

**Comment by chef4brains** [comment]
Bitcoin Knots will soon be available on Start9.

https://x.com/start9labs/status/1761753415217291759?s=46

**Comment by humansinstitute** [comment]
Coinbase having trouble keeping it up ;-)

Coinbase Stabilizes After Experiencing Downtime, Glitches Due to Heavy Traffic

https://www.nobsbitcoin.com/coinbase-restabilized-after-heavy-traffic-causes-issues/

**Comment by humansinstitute** [comment]
Allan trolls BITVM but is kinda close to what is a very interesting solution in Carol (see video) 

- https://dlcvm.tiiny.site/
- https://www.youtube.com/watch?v=hCjbStBKCEQ

**Comment by NoSandMan** [comment]
List of best resources to give to new Bit-coiners

**Comment by humansinstitute** [comment]
Bitcoin bigger than the pound??

https://x.com/1basemoney/status/1762769511025967219?s=46

**Comment by humansinstitute** [comment]
How to convince the spouse - lol
