### ISSUE TITLE
2024-04 April BitDevs!

### ISSUE THREAD

**Issue by NoSandMan** [PerthBitDevs/PerthBitDevs#6]
Perth BitDevs - Bitcoin Socratic Seminar - 4th April 2024!

Thu, Apr 4 · 6:00 PM AWST at Phat Brew Brewery in City West.

Please leave discussion topics below.

**Comment by humansinstitute** [comment]
Hedgehog!

Super testnet with another invention this time giving us asynchronous payment channels. 

Big news. 

https://x.com/super_testnet/status/1772647977892405739?s=46

**Comment by humansinstitute** [comment]
Sigbash from Arbedout. 

Private server side Multisite spending rules. (I think need to dig in more). 

Think Covenants but as a server. 

https://x.com/arbedout/status/1772646219317174680?s=46

**Comment by humansinstitute** [comment]
Runes

Probably not something to spend long on,  it this is going to launch at the halving so might be worth covering as it's likely fees are going to go mental.

https://x.com/rodarmor/status/1772739766657692022?s=46

**Comment by NoSandMan** [comment]
Saylor copy cat? 

Micro cap stock announcement of intention to purchase bitcoin. This one looks like a hail Mary but the next ones might not be. 

https://x.com/BitcoinNewsCom/status/1772696210882621879?s=20

**Comment by NoSandMan** [comment]
> Runes
> 
> Probably not something to spend long on, it this is going to launch at the halving so might be worth covering as it's likely fees are going to go mental.
> 
> https://x.com/rodarmor/status/1772739766657692022?s=46

This + ordinals may incentivise re orgs in the first few block after the halving. Worth a chat about.

**Comment by NoSandMan** [comment]
![image](https://github.com/humansinstitute/PerthBitDevs/assets/104331906/e9625169-e231-444b-b66c-463e8efc983c)

**Comment by chef4brains** [comment]
Ably extension will be available for iOS! 

https://damus.io/nevent1qqsx7a26ft379cwjh8fad80u729yk8a9q340l3y9u7ae658xksgz7zqppamhxue69uhkummnw3ezumt0d5q32amnwvaz7tm9v3jkutnwdaehgu3wd3skueqprpmhxue69uhhyetvv9ujumn0wd68ytnrdakjuct4qyv8wumn8ghj7un9d3shjtnwdaehgunpw35jucm0d5k0thkw

**Comment by humansinstitute** [comment]
OpenSSH hack. 

Long term contributor sneaks backdoor into ssh / C++ - ongoing needs some investigation

https://x.com/dpc_pw/status/1773912758217773115?s=46

**Comment by chef4brains** [comment]
How to verify Seedsigner software with GPG on Mac/linux. 

https://github.com/SeedSigner/seedsigner

**Comment by humansinstitute** [comment]
Cashu multinuteral payments

Many mints to 1 invoice. Why and how. 

https://x.com/callebtc/status/1766116631795662921?s=46

**Comment by humansinstitute** [comment]
History lesson

The 21 million bip 

https://github.com/bitcoin/bips/blob/master/bip-0042.mediawiki
