### ISSUE TITLE
2024-05 May Bitdevs

### ISSUE THREAD

**Issue by humansinstitute** [PerthBitDevs/PerthBitDevs#7]
May Bitdevs!

**Comment by humansinstitute** [comment]
Side pools 

UTXO sharing and lightning by Zman. 

https://x.com/jxpcsnmz/status/1776533544367776068?s=46

**Comment by chef4brains** [comment]
Has ₿ been co-opted? 

https://x.com/mononautical/status/1777686545715089605?s=46

**Comment by chef4brains** [comment]
BTC backed USD. 

https://x.com/callebtc/status/1777598819355496587?s=46

**Comment by humansinstitute** [comment]
Bit VM - Insecure?

https://x.com/dr_dao_/status/1776240444843741245?s=46

Interesting thoughts from Alex B on Bitcoin.Review starts around 20 mins

https://pca.st/episode/dbaa17e4-c86a-4225-9b71-ab450ecb61dd?t=1961.0

**Comment by humansinstitute** [comment]
Ossification versus Changes to Bitcoin

- Soft forks
- Maintenance 
- Great consensus clean up (hard fork)

**Comment by humansinstitute** [comment]
Why the fee spike


https://x.com/btcgandalf/status/1781605750617309446?s=46

**Comment by humansinstitute** [comment]
Zero knowledge coins

https://gist.github.com/RobinLinus/d036511015caea5a28514259a1bab119

https://x.com/robin_linus/status/1781832291938877704?s=46

**Comment by chef4brains** [comment]
Migrate from Samurai to Sparrow. 

https://x.com/_k3tan/status/1783389500485578847?s=46

**Comment by chef4brains** [comment]
Antminer S9 breakdown demo.
