### ISSUE TITLE
2024 - 06 June Bitdevs

### ISSUE THREAD

**Issue by humansinstitute** [PerthBitDevs/PerthBitDevs#9]
Perth BitDevs - Bitcoin Socratic Seminar - 6th June 2024!

Thu, Jun 6 · 6:00 PM AWST at Phat Brew Brewery in City West.

Please leave discussion topics below.

**Comment by humansinstitute** [comment]
Axiom of resistance

**Comment by chef4brains** [comment]
Decentralised whirlpools with Sparrow. 

https://x.com/sparrowwallet/status/1778383369505517718?s=46

**Comment by chef4brains** [comment]
Coldcard Q and MK4 firmware upgrade. 

https://x.com/COLDCARDwallet/status/1787564608313541010

**Comment by humansinstitute** [comment]
Key chat signal on nostr???

https://www.keychat.io/

https://primal.net/e/note1kr8nvdlhz207rq6z300xy6qylf9mmpgjxgfq6925vkez4f3ej3gqh5f0te

**Comment by murray-mcphee** [comment]
Liking Nostr, yes

**Comment by humansinstitute** [comment]
Peter's Ruling Tornado Cash

Chilling effect

https://x.com/arbedout/status/1790363082172019195?s=46

**Comment by btc-alchemist** [comment]
Silent Payments: BIP352

**Comment by chef4brains** [comment]
> Silent Payments: BIP352

https://bips.dev/352/

**Comment by NoSandMan** [comment]
Bitcoin game theory. Trump and the great wedge.

**Comment by NoSandMan** [comment]
Scaling Bitcoin why bitcoin banks are not enough.

**Comment by humansinstitute** [comment]
Similar angle on "Upgrades, Ossification etc"

**Comment by humansinstitute** [comment]
The Great Script Restoration Project

https://bitcoinmagazine.com/technical/the-great-script-restoration-a-path-forward-for-bitcoin

https://primal.net/p/npub179e9tp4yqtqx4myp35283fz64gxuzmr6n3yxnktux5pnd5t03eps0elz4s

**Comment by humansinstitute** [comment]
ROASTr
https://stacker.news/items/524728

**Comment by chef4brains** [comment]
Corny chat: a nostr client with baked in V4V. 

https://primal.net/e/note1s6m4j4ufnhj66x2zms69rw0wjhawnau6xv7x7gz0dxrrsyldlurqzmeqdj

**Comment by chef4brains** [comment]
NerdAXE released!

https://x.com/BitMaker_/status/1793762401743229038

**Comment by chef4brains** [comment]
Bitmain fuckery!

https://x.com/GrassFedBitcoin/status/1796311998466003418

**Comment by chef4brains** [comment]
Wasabi wallet update

https://blog.wasabiwallet.io/wasabi-wallet-2-0-8-release-post/
